spring:
  servlet:
    multipart:
      max-file-size: 500MB
      max-request-size: 500MB
spring.jpa:
  database: POSTGRESQL
  hibernate.ddl-auto: update
  show-sql: true
  hibernate.naming.physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

spring.datasource:
  driverClassName: org.postgresql.Driver
  url: jdbc:postgresql://localhost:5432/tts
  username: postgres
  password: password
  
server:
  port : 8080
  
file:
  base-path: D:/demo/tts
  upload-url: http://localhost:8080/uploadfile/ttsms/upload
  

