spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: asdeshmukh0710@gmail.com
    password: cpyxznmxzdcsgpxx
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

spring.datasource:
  driverClassName: org.postgresql.Driver
  url: jdbc:postgresql://localhost:5432/tts
  username: postgres
  password: Pass1word
