spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: cloudpointsystem7@gmail.com
    password: zqappnbhzyzyxrsf
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

spring.datasource:
  driverClassName: org.postgresql.Driver
  url: jdbc:postgresql://44.193.95.50:5432/tts
  username: postgres
  password: "7$Rt6&m,6&Ui4!as9^Yu2"

#server:
#  port: 8080

server:
  port: 8443
  ssl:
    key-store-type: PKCS12
    key-store: src/main/resources/keystore/ttscertificate.p12
    key-store-password: sslpassword
    key-alias: ttscertificate
