spring:
  servlet:
    multipart:
      max-file-size: 500MB
      max-request-size: 500MB
spring.jpa:
  database: POSTGRESQL
  hibernate.ddl-auto: update
  show-sql: true
  hibernate.naming.physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

spring.datasource:
  driverClassName: org.postgresql.Driver
  url: jdbc:postgresql://localhost:5432/tts
  username: postgres
  password: "7$Rt6&m,6&Ui4!as9^Yu2"
  
server:
  port: 8443
  ssl:
      key-store-type : PKCS12
      key-store : src/main/resources/keystore/tomcatkey.p12
      key-store-password: sslpassword
      key-alias : tomcatkey
  

file:
  base-path: D:/demo/tts

  # Define the URLs for external services
external-services:
  reason-api-url: https://localhost:8443/reason/ttsms/reason
  upload-file-url: https://localhost:8443/uploadfile/ttsms/upload
  email-url: https://localhost:8443/email/taskMail
  employee-url: https://localhost:8443/employee/ttsms/employee/
  status-url: https://localhost:8443/status/ttsms/status/
  task-url: https://localhost:8443/task/ttsms/task/
