spring:
  servlet:
    multipart:
      max-file-size: 500MB
      max-request-size: 500MB
spring.jpa:
  database: POSTGRESQL
  hibernate.ddl-auto: update
  show-sql: true
  hibernate.naming.physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

spring.datasource:
  driverClassName: org.postgresql.Driver
  url: jdbc:postgresql://127.0.0.1:5432/tts
  username: postgres
  password: "7$Rt6&m,6&Ui4!as9^Yu2"

#server:
#  port: 8080

server:
  port: 8443
  ssl:
    key-store-type: PKCS12
    key-store: src/main/resources/keystore/ttscertificate.p12
    key-store-password: sslpassword
    key-alias: ttscertificate

file:
  base-path: /demo/tts

  # Define the URLs for external services
external-services:
  reason-api-url: https://127.0.0.1:8443/reason/ttsms/reason
  upload-file-url: https://127.0.0.1:8443/uploadfile/ttsms/upload
  email-url: https://127.0.0.1:8443/email/taskMail
  employee-url: https://127.0.0.1:8443/employee/ttsms/employee/
  status-url: https://127.0.0.1:8443/status/ttsms/status/
  task-url: https://127.0.0.1:8443/task/ttsms/task/
