spring:
  servlet:
    multipart:
      max-file-size: 500MB
      max-request-size: 500MB
spring.jpa:
  database: POSTGRESQL
  hibernate.ddl-auto: update
  show-sql: true
  hibernate.naming.physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

spring.datasource:
  driverClassName: org.postgresql.Driver
  url: jdbc:postgresql://localhost:5432/tts
  username: postgres
  password: "7$Rt6&m,6&Ui4!as9^Yu2"

server:
  port: 8080

file:
  base-path: D:/demo/tts

  # Define the URLs for external services
external-services:
  reason-api-url: http://localhost:8080/reason/ttsms/reason
  upload-file-url: http://localhost:8080/uploadfile/ttsms/upload
  email-url: http://localhost:8080/email/taskMail
  employee-url: http://localhost:8080/employee/ttsms/employee/
  status-url: http://localhost:8080/status/ttsms/status/
  task-url: http://localhost:8080/task/ttsms/task/
