#root folder - where to generate the code
rootFolder=D:/TTS/TTS/BE/tts_ms/services/

# Service name in Camel Case
Cservice=LeadGeneration

# Service name in small case
service=leadgeneration

# module name
module=LeadGeneration

#uri name - common for all the curd services
uri=leadgeneration

#parameter name - common for put, delete and get
param=locationId

#Code Generation Date
genDate=19/12/2023

#Entity Class Name
entity=leadgeneration

#Table name
TableName=leadrepo

#Find by column name 
findBy=locationId
