spring:
  servlet:
    multipart:
      max-file-size: 500MB
      max-request-size: 500MB
  jpa:
    database: POSTGRESQL
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://127.0.0.1:5432/tts
    username: postgres
    password: "7$Rt6&m,6&Ui4!as9^Yu2"

#server:
#  port: 8080

server:
  port: 8443
  ssl:
    key-store-type: PKCS12
    key-store: src/main/resources/keystore/ttscertificate.p12
    key-store-password: sslpassword
    key-alias: ttscertificate

file:
  base-path: /demo/tts
